### ISSUE TITLE
[TEAM A] [ FEEDBACK] Determine if Section 3.2.2 is Necessary

### ISSUE THREAD

**Issue by b2af** [umgc/Summer2024#116]
![Image](https://github.com/umgc/Summer2024/assets/35238594/09d3a155-0373-42b4-bcf2-2a43497a0230)

**Comment by lariasse** [comment]
We don't need email connectivity in 3.2.2 of the project plan.

**Comment by b2af** [comment]
Make the necessary changes in the PMP.
