### ISSUE TITLE
[Team C] [Task] - [Plugin Testing and Deploy] Integration Testing

### ISSUE THREAD

**Issue by WhitneyMeulink** [umgc/Summer2024#254]
Test the plugins in a staging environment to ensure seamless integration with Moodle.

- [x] #376
- [x] #377
- [x] #378

**Comment by StephenBuley** [comment]
- [ ] Add GitHub CI/CD Pipeline for integration testing
- [ ] Add example tests
- [ ] Test CI/CD Pipeline using example tests
