### ISSUE TITLE
[Team C] [Feature] Test Creation and Management - Specify test details

### ISSUE THREAD

**Issue by WhitneyMeulink** [umgc/Summer2024#256]
- [x] #402
- [x] #403
- [x] #404
- [x] #405

**Comment by StephenBuley** [comment]
- [ ] [Team C] [Task] - [Specify Test Details] Create view for "Create base Assessment" page
- [ ] [Team C] [Task] - [Specify Test Details] Hook up "Create base Assessment" view to Moodle
- [ ] [Team C] [Task] - [Specify Test Details] Create view for "Add Questions" page
- [ ] [Team C] [Task] - [Specify Test Details] Hook up "Add Questions" view to LLM
